import { Config } from 'src/providers/ConfigProvider';

const {
  VITE_BASE_URL_API,
  VITE_BUILD_DATE,
  VITE_BUILD_TIME,
  VITE_BUILD_TS,
  VITE_BUILD_COMMIT_SHA,
  VITE_BUILD_ENV_CODE,
  VITE_BUILD_WORKFLOW_NAME,
  VITE_BUILD_WORKFLOW_RUN_NUMBER,
  VITE_BUILD_WORKFLOW_RUN_ATTEMPT,
  VITE_TOAST_AUTO_DISMISS_MILLIS,
} = import.meta.env;

export const config: Config = {
  VITE_BASE_URL_API,
  VITE_BUILD_DATE,
  VITE_BUILD_TIME,
  VITE_BUILD_TS,
  VITE_BUILD_COMMIT_SHA,
  VITE_BUILD_ENV_CODE,
  VITE_BUILD_WORKFLOW_NAME,
  VITE_BUILD_WORKFLOW_RUN_NUMBER,
  VITE_BUILD_WORKFLOW_RUN_ATTEMPT,
  VITE_TOAST_AUTO_DISMISS_MILLIS,
};
